### ISSUE TITLE
I have a question about implementing it with the STM32 series.

### ISSUE THREAD

**Issue by cheoljun99** [JorgeMaker/CanSnifferSuite#1]
Hello, I found the CanSnifferSuite project while looking for the CANSNiffer open source project. I am impressed by the project and am in the process of implementing it.

I also have a few questions. They are as follows:

1. I have a stm32f401ccu6 board, but this board does not support CAN communication. Therefore, I want to implement the project by connecting the MCP2515, but I wonder if there are any restrictions.

2. If I want to use RTOS to implement the project, do I have to use stm32f407vgt6 unconditionally, and if I want to implement it without RTOS, do I have to use stm32f103c8t6 unconditionally?

3. I am wondering if there is an alternative board that can be installed with RTOS and apply the corresponding open source code (STM32F4 series)
I am wondering if there is an alternative board that can be installed with open source code without installing RTOS (STM32F1 series)

**Comment by JorgeMaker** [comment]
Hi @cheoljun99,

I'm responding to your questions below:

If your microcontroller doesn’t have native CAN communications, you'll need to implement sending and receiving CAN frames through an SPI driver that allows communication with the MCP2515. It’s completely possible to do, although it will require more work. As far as I know, there shouldn’t be any type of restriction.

Not at all, in this implementation those two microcontrollers were used simply because they were the ones I had on hand, but STM provides, through their development tools, the necessary environment to implement the functionality on any other microcontroller for which they support FreeRTOS.

The code for this project is designed to work with the STM32 HAL... it should be very easy to port it to other microcontrollers, even from different families, by adapting the Pinout and making sure everything continues to function correctly.

DISCLAIMER: The project has not been fully tested; it works correctly, but it still needs to be tested thoroughly under high message load conditions, both the Firmware part and the software part that receives the messages and displays them in the Python-implemented application.

I hope it helps !!!

Best Regards
JSLL

**Comment by cheoljun99** [comment]
Hello @JorgeMaker

Thanks for your reply. It was helpful.

Best Regards,
Cheoljun
